### ISSUE TITLE
Error when compiling after building .dll

### ISSUE THREAD

**Issue by Vejas04** [mojtaba-brz/Rainbow-Trading-Pairs#1]
Hello, after trying to build the mq5 file I get this error when compiling: 
'MainTRBotEA.mq5'			1
'AllNeededLibs.mqh'			1
'TimeUtils.mqh'			1
'typedefs.mqh'			1
'TrBotClient.mqh'			1
'MessagesLib.mqh'			1
'Data2StateTransformationTools.mqh'			1
file 'C:\Users\vejas\AppData\Roaming\MetaQuotes\Terminal\73B7A2420D6397DFF9014A20F1201F97\MQL5\Shared Projects\MQL5SideEA\MQL_Easy\MQL_Easy\MQL_Easy.mqh' not found	Data2StateTransformationTools.mqh	8	11
'Math.mqh'			1
'RiskManagement.mqh'			1
'TradeManagement.mqh'			1
file 'C:\Users\vejas\AppData\Roaming\MetaQuotes\Terminal\73B7A2420D6397DFF9014A20F1201F97\MQL5\Shared Projects\MQL5SideEA\MQL_Easy\MQL_Easy\MQL_Easy.mqh' not found	AllNeededLibs.mqh	20	11
'OnInit' - function already defined and has body	MainTRBotEA.mq5	83	5
   see declaration of function 'OnInit'	MainTRBotEA.mq5	24	5
'OnDeinit' - function already defined and has body	MainTRBotEA.mq5	94	6
   see declaration of function 'OnDeinit'	MainTRBotEA.mq5	32	6
'OnTick' - function already defined and has body	MainTRBotEA.mq5	103	6
   see declaration of function 'OnTick'	MainTRBotEA.mq5	39	6
'CPosition' - undeclared identifier	Data2StateTransformationTools.mqh	37	4
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	37	14
'cp' - some operator expected	Data2StateTransformationTools.mqh	37	14
',' - unexpected token	Data2StateTransformationTools.mqh	37	23
expression has no effect	Data2StateTransformationTools.mqh	37	17
')' - unexpected token	Data2StateTransformationTools.mqh	37	30
expression has no effect	Data2StateTransformationTools.mqh	37	25
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	39	7
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	41	22
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	53	10
'CPosition' - undeclared identifier	Data2StateTransformationTools.mqh	65	4
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	65	14
'cp' - some operator expected	Data2StateTransformationTools.mqh	65	14
',' - unexpected token	Data2StateTransformationTools.mqh	65	23
expression has no effect	Data2StateTransformationTools.mqh	65	17
')' - unexpected token	Data2StateTransformationTools.mqh	65	30
expression has no effect	Data2StateTransformationTools.mqh	65	25
'cp' - undeclared identifier	Data2StateTransformationTools.mqh	66	11
'CExecute' - undeclared identifier	TradeManagement.mqh	23	4
'ex1' - undeclared identifier	TradeManagement.mqh	23	13
'ex1' - some operator expected	TradeManagement.mqh	23	13
',' - unexpected token	TradeManagement.mqh	23	23
expression has no effect	TradeManagement.mqh	23	17
')' - unexpected token	TradeManagement.mqh	23	30
expression has no effect	TradeManagement.mqh	23	25
'CExecute' - undeclared identifier	TradeManagement.mqh	24	4
'ex2' - undeclared identifier	TradeManagement.mqh	24	13
'ex2' - some operator expected	TradeManagement.mqh	24	13
',' - unexpected token	TradeManagement.mqh	24	23
expression has no effect	TradeManagement.mqh	24	17
')' - unexpected token	TradeManagement.mqh	24	34
expression has no effect	TradeManagement.mqh	24	31
'ex1' - undeclared identifier	TradeManagement.mqh	32	4
'ex2' - undeclared identifier	TradeManagement.mqh	34	4
'CExecute' - undeclared identifier	TradeManagement.mqh	42	4
'ex1' - undeclared identifier	TradeManagement.mqh	42	13
'ex1' - some operator expected	TradeManagement.mqh	42	13
',' - unexpected token	TradeManagement.mqh	42	23
expression has no effect	TradeManagement.mqh	42	17
')' - unexpected token	TradeManagement.mqh	42	30
expression has no effect	TradeManagement.mqh	42	25
'CExecute' - undeclared identifier	TradeManagement.mqh	43	4
'ex2' - undeclared identifier	TradeManagement.mqh	43	13
'ex2' - some operator expected	TradeManagement.mqh	43	13
',' - unexpected token	TradeManagement.mqh	43	23
expression has no effect	TradeManagement.mqh	43	17
')' - unexpected token	TradeManagement.mqh	43	34
expression has no effect	TradeManagement.mqh	43	31
'ex1' - undeclared identifier	TradeManagement.mqh	50	4
'ex2' - undeclared identifier	TradeManagement.mqh	52	4
'CPosition' - undeclared identifier	TradeManagement.mqh	58	4
'cp1' - undeclared identifier	TradeManagement.mqh	58	14
'cp1' - some operator expected	TradeManagement.mqh	58	14
',' - unexpected token	TradeManagement.mqh	58	24
expression has no effect	TradeManagement.mqh	58	18
')' - unexpected token	TradeManagement.mqh	58	31
expression has no effect	TradeManagement.mqh	58	26
',' - unexpected token	TradeManagement.mqh	58	32
'cp2' - undeclared identifier	TradeManagement.mqh	58	34
',' - unexpected token	TradeManagement.mqh	58	44
'symbol' - some operator expected	TradeManagement.mqh	58	38
')' - unexpected token	TradeManagement.mqh	58	55
expression has no effect	TradeManagement.mqh	58	54
'cp1' - undeclared identifier	TradeManagement.mqh	59	4
'cp2' - undeclared identifier	TradeManagement.mqh	60	4
'CPosition' - undeclared identifier	TradeManagement.mqh	66	4
'cp1' - undeclared identifier	TradeManagement.mqh	66	16
'cp1' - some operator expected	TradeManagement.mqh	66	16
',' - unexpected token	TradeManagement.mqh	66	26
expression has no effect	TradeManagement.mqh	66	20
')' - unexpected token	TradeManagement.mqh	66	33
expression has no effect	TradeManagement.mqh	66	28
',' - unexpected token	TradeManagement.mqh	66	34
'cp2' - undeclared identifier	TradeManagement.mqh	67	16
',' - unexpected token	TradeManagement.mqh	67	26
'symbol' - some operator expected	TradeManagement.mqh	67	20
')' - unexpected token	TradeManagement.mqh	67	37
expression has no effect	TradeManagement.mqh	67	36
'cp1' - undeclared identifier	TradeManagement.mqh	75	10
'cp1' - undeclared identifier	TradeManagement.mqh	80	13
67 errors, 18 warnings		68	19
Building the .dll went fine.

**Comment by mojtaba-brz** [comment]
Hello,
I guess you didn't clone this repository using --recursive flag.
Try "git submodule update --init --recursive" or just clone using
--recursive flag.

**Comment by Vejas04** [comment]
Hey,
no the error still persists.

**Comment by mojtaba-brz** [comment]
Hey,
I fixed it in the last commit. I had forgotten to add the "MQL_Easy" submodule to the project. 
Let me know if there are any other problems.

**Comment by mojtaba-brz** [comment]
Thanks to "[Vejas04](https://github.com/Vejas04)" for their interest
